### PR TITLE
Add zero or one space(s) to streetname regex

### PR DESCRIPTION
**Pull request by Jeroenll**

### CODE REVIEW

**Comment by JeroenVanLeusden** [comment]
hhvm build fails (not related to this change), should we remove this entirely?

**Comment by pkruithof** [comment]
Yes, hhvm is not something we want to support at this point.

**Review by pkruithof — APPROVED** [review]

**Comment by pkruithof** [comment]
@fieg lgtm

**Review by fieg — APPROVED** [review]
lgtm 2

**Comment by pkruithof** [comment]
Thanks @JeroenVanLeusden! 

I've released v1.0.4 with this change.

**Pull request merged**
